config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :stocks do
    member {get :send_img}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all

    # 表示用書式に編集
    @stocks.each do |stock|
      stock.code = stock.code.floor
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    # respond_to:1つのアクションから複数のフォーマットで返す
    respond_to do |format|
      if @stock.update(stock_params)
      
        # 写真のアップロードと保存
        if params[:stock].has_key? :picture
          @stock.picture = params[:stock]["picture"].read
          @stock.filename = params[:stock]["picture"].original_filename
          @stock.save
        end

        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # 写真の画像表示
  def send_img
    @stock = set_stock

    if @stock.picture != nil
      send_data @stock.picture, type: "image/jpeg", disposition: :inline
    end
  end

  # メンバーメソッド
private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # stockモデルに関係のある変数のみを記載する。直接テーブルにUpdate可能となる。
    def stock_params
      params.require(:stock).permit(:name, :code, :buydate, :buynum, :buyprice, :selldate, :sellnum, :sellprice, :note, :judge, :profitloss)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kabu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :buydate %>
    <%= form.datetime_select :buydate %>
  </div>

  <div class="field">
    <%= form.label :buynum %>
    <%= form.number_field :buynum %>
  </div>

  <div class="field">
    <%= form.label :buyprice %>
    <%= form.number_field :buyprice %>
  </div>

  <div class="field">
    <%= form.label :selldate %>
    <%= form.datetime_select :selldate %>
  </div>

  <div class="field">
    <%= form.label :sellnum %>
    <%= form.number_field :sellnum %>
  </div>

  <div class="field">
    <%= form.label :sellprice %>
    <%= form.number_field :sellprice %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :judge %>
    <%= form.number_field :judge %>
  </div>

  <div class="field">
    <%= form.label :profitloss %>
    <%= form.number_field :profitloss %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <button type="button" class="btn vtn-primary">更新</button>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- BootstrapのCSS読み込み -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- jQuery読み込み -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <!-- BootstrapのJS読み込み -->
    <!-- <script src="js/bootstrap.min.js"></script> -->
  <title>株あがれ</title>
  <style type="text/css">
    .jumbotron {background: url("<%= asset_path "kabu_top_m.jpg" %>") center no-repeat; background-size: cover;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">株あがれ。</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="<%= stocks_path %>">Search/Index <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_stock_path %>">Add</a>
    </li>
  </ul>
</div>
</nav>
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<% @stocks.each do |stock| %>
  <div class="container border rounded" style="background-color:#fafafe">
    <div align="right" class="border-bottom">
      <%= link_to 'Show', stock %> | 
      <%= link_to 'Edit', edit_stock_path(stock) %> | 
      <%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="row border-bottom">
      <div class="col-1">ID</div>
      <div class="col">名前</div>
      <div class="col">コード</div>
    </div>
    <div class="row mb-1 border-bottom">
      <div class="col-1"><%= stock.id %></div>
      <div class="col"><%= stock.name %></div>
      <div class="col"><%= stock.code %></div>
    </div>
    <div class="row border-bottom">
      <div class="col">
        買い情報
      </div>
      <div class="col">
        売り情報
      </div>
    </div>
    <div class="row">
      <div class="col">
        購入日時:
      </div>
      <div class="col">
        取得数:
      </div>
      <div class="col">
        取得額:
      </div>
      <div class="col">
        売却日時:
      </div>
      <div class="col">
        売却数:
      </div>
      <div class="col">
        売却額:
      </div>
    </div>
    <div class="row border-bottom">
      <div class="col">
        <%= stock.buydate %>
      </div>
      <div class="col">
        <%= stock.buynum %>
      </div>
      <div class="col">
        <%= stock.buyprice %>
      </div>
      <div class="col">
        <%= stock.selldate %>
      </div>
      <div class="col">
        <%= stock.sellnum %>
      </div>
      <div class="col">
        <%= stock.sellprice %>
      </div>
    </div>
     <div class="row border-bottom">
      <div class="col">
        チャート
        <%= 
          if stock.picture != nil 
            image_tag send_img_stock_path(stock.id), :class => "img-thumbnail"
          end 
        %>
      </div>
      <div class="col">
        ノート：
        <p><%= stock.note %></p>
      </div>
    </div>
    <br>
  </div>
<% end %>

<div class="container">
  <table>
  <thead>
    <tr>
      <th>名前</th>
      <th>コード</th>
      <th>取得日時</th>
      <th>取得数</th>
      <th>取得額</th>
      <th>売却日時</th>
      <th>売却数</th>
      <th>売却額</th>
      <th>ノート</th>
      <th>確度</th>
      <th>評価損益</th>
      <th>ファイル名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.code %></td>
        <td><%= stock.buydate %></td>
        <td><%= stock.buynum %></td>
        <td><%= stock.buyprice %></td>
        <td><%= stock.selldate %></td>
        <td><%= stock.sellnum %></td>
        <td><%= stock.sellprice %></td>
        <td><%= stock.note %></td>
        <td><%= stock.judge %></td>
        <td><%= stock.profitloss %></td>
        <td><%= stock.filename %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<br>

<%= link_to '株情報の追加', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Buydate:</strong>
  <%= @stock.buydate %>
</p>

<p>
  <strong>Buynum:</strong>
  <%= @stock.buynum %>
</p>

<p>
  <strong>Buyprice:</strong>
  <%= @stock.buyprice %>
</p>

<p>
  <strong>Selldate:</strong>
  <%= @stock.selldate %>
</p>

<p>
  <strong>Sellnum:</strong>
  <%= @stock.sellnum %>
</p>

<p>
  <strong>Sellprice:</strong>
  <%= @stock.sellprice %>
</p>

<p>
  <strong>Note:</strong>
  <%= @stock.note %>
</p>

<p>
  <strong>Judge:</strong>
  <%= @stock.judge %>
</p>

<p>
  <strong>Profitloss:</strong>
  <%= @stock.profitloss %>
</p>

<p>
  <strong>Picture:</strong>
    <%= 
      if @stock.picture != nil 
        image_tag send_img_stock_path(@stock.id), :class => "img-thumbnail"
      end 
    %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @stock.filename %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/top/index.html.erb
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- BootstrapのCSS読み込み -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- jQuery読み込み -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <!-- BootstrapのJS読み込み -->
    <!-- <script src="js/bootstrap.min.js"></script> -->
  <title>株あがれ</title>
  <style type="text/css">
    .jumbotron {background: url("<%= asset_path "kabu_top_m.jpg" %>") center no-repeat; background-size: cover;}
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">株あがれ。</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= stocks_path %>">Search/Index</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_stock_path %>">Add</a>
    </li>
  </ul>
</div>
</nav>
<div class="jumbotron">
  <div class="container text-light">
    <h1>株購入日誌</h1>
    これまで購入した株について整理。
  </div>
  <div class="container text-light">
    <h4>更新履歴</h4>
    <ul>
    <li>
    <2018.12.07>サイト新規作成
    </li>
    </ul>
  </div>
</div>
<h1>総合評価</h1>
全体件数 | 勝ち数 | 負け数 | 勝率<br>
<h2>評価損益</h2>
総合評価損益（登録データ分）
<hr>
<h3>タスク</h3>
<ul>
  <li>チャートの拡大表示対応。</li>
  <li>評価損益の表示。</li>
</ul>